package Game.Buildings;

import Exceptions.BuildingException;
import Game.People.Citizen;
import Game.Resource;

import java.util.ArrayList;
import java.util.HashMap;

public abstract class Building {
    private String name;
    private int workersCapacity;
    private int citizensCapacity;
    private int buildingTime;
    private int level;
    private int goldCost;
    private HashMap<Resource, Integer> resourcesNeeded;
    private HashMap<Resource, Integer> resourcesConsumption;
    private HashMap<Resource, Integer> resourcesGenerating;

    private int citizensCount;
    private int workersCount;
    private ArrayList<Citizen> citizens;
    private ArrayList<Citizen> workers;

    /*
    * Constructor for Building abstract class
    * @param name Name of the building
    * @param workersCapacity Maximum number of workers that can work in the building
    * @param citizensCapacity Maximum number of citizens that can live in the building
    * @param buildingTime Time needed to build the building
    * @param level Level of the building
    * @param goldCost Gold cost of the building
    */
    public Building(String name, int workersCapacity, int citizensCapacity, int buildingTime, int level, int goldCost) {
        this.name = name;
        this.workersCapacity = workersCapacity;
        this.citizensCapacity = citizensCapacity;
        this.buildingTime = buildingTime;
        this.level = level;
        this.goldCost = goldCost;
        this.resourcesConsumption = new HashMap<>();
        this.resourcesNeeded = new HashMap<>();
        this.resourcesGenerating = new HashMap<>();
        this.citizens = new ArrayList<>();
        this.workers = new ArrayList<>();
        this.citizensCount = 0;
        this.workersCount = 0;
    }

    /*
    * Returns the name of the building
    * */
    public String getName() {
        return name;
    }

    /*
     * Returns the maximum number of workers that can work in the building
     * */
    public int getWorkersCapacity() {
        return workersCapacity;
    }

    /*
     * Set the maximum number of workers that can work in the building
     * @param workersCapacity Maximum number of workers that can work in the building
     * */
    public void setWorkersCapacity(int workersCapacity) {
        this.workersCapacity = workersCapacity;
    }

    /*
     * Returns the maximum number of citizens that can live in the building
     * */
    public int getCitizensCapacity() {
        return citizensCapacity;
    }

    /*
     * Set the maximum number of citizens that can live in the building
     * @param citizensCapacity Maximum number of citizens that can live in the building
     * */
    public void setCitizensCapacity(int citizensCapacity) {
        this.citizensCapacity = citizensCapacity;
    }

    /*
     * Returns the time needed to build the building (in rounds)
     * */
    public int getBuildingTime() {
        return buildingTime;
    }

    /*
     * Set the time needed to build the building (in rounds)
     * @param buildingTime Time needed to build the building (in rounds)
     * */
    public void setBuildingTime(int buildingTime) {
        this.buildingTime = buildingTime;
    }

    /*
     * Returns the level of the building
     * */
    public int getLevel() {
        return level;
    }

    /*
     * Set the level of the building
     * @param level Level of the building
     * */
    public void setLevel(int level) {
        this.level = level;
    }

    /*
     * Returns the gold cost of the building
     * */
    public int getGoldCost() {
        return goldCost;
    }

    /*
     * Set the gold cost of the building
     * @param goldCost Gold cost of the building
     * */
    public void setGoldCost(int goldCost) {
        this.goldCost = goldCost;
    }

    /*
     * Returns the HashMap of resources needed to build the building
     * */
    public HashMap<Resource, Integer> getResourcesNeeded() {
        return resourcesNeeded;
    }

    /*
     * Set the HashMap of resources needed to build the building
     * */
    public void setResourcesNeeded(HashMap<Resource, Integer> resourcesNeeded) {
        this.resourcesNeeded = resourcesNeeded;
    }

    /*
     * Returns the HashMap of resources consumed by the building each round
     * */
    public HashMap<Resource, Integer> getResourcesConsumption() {
        return resourcesConsumption;
    }

    /*
     * Set the HashMap of resources consumed by the building each round
     * @param resourcesConsumption HashMap of resources consumed by the building each round
     * */
    public void setResourcesConsumption(HashMap<Resource, Integer> resourcesConsumption) {
        this.resourcesConsumption = resourcesConsumption;
    }

    /*
     * Returns the HashMap of resources generated by the building each round
     * */
    public HashMap<Resource, Integer> getResourcesGenerating() {
        return resourcesGenerating;
    }

    /*
     * Set the HashMap of resources generated by the building each round
     * @param resourcesGenerating HashMap of resources generated by the building each round
     * */
    public void setResourcesGenerating(HashMap<Resource, Integer> resourcesGenerating) {
        this.resourcesGenerating = resourcesGenerating;
    }

    /*
     * Returns the ArrayList of citizens living in the building
     * */
    public void addCitizen(Citizen citizen) {
        if (this.citizensCount < this.citizensCapacity) {
            this.citizens.add(citizen);
            this.citizensCount++;
            citizen.setHome(this);
            System.out.println("Citizen added");
        } else {
            throw new BuildingException("Citizen capacity of  " + this.getName() + " reached");
        }
    }

    /*
     * Add a worker to the building
     * @param citizen Citizen to add as a worker
     * */
    public void addWorker(Citizen citizen) {
        if (this.workersCount < this.workersCapacity) {
            this.workers.add(citizen);
            this.workersCount++;
            System.out.println("Worker added");
            citizen.setWorkplace(this);
        } else {
            throw new BuildingException("Worker capacity of  " + this.getName() + " reached");
        }
    }

    /*
     * Remove a citizen from the building
     * @param citizen Citizen to remove
     * */
    public void removeCitizen(Citizen citizen) {
        if (this.citizensCount > 0) {
            for (int i = 0; i < this.citizensCount; i++) {
                if (this.citizens.get(i).getId() == citizen.getId()) {
                    this.citizens.remove(i);
                    this.citizensCount--;
                    this.citizens.get(i).setHome(null);
                    System.out.println("Citizen removed");
                    break;
                }
            }
            throw new BuildingException("Citizen not found");
        } else {
            throw new BuildingException("No citizen to remove");
        }
    }

    /*
     * Remove a worker from the building
     * @param citizen Citizen to remove
     * */
    public void removeWorker(Citizen citizen) {
        if (this.workersCount > 0) {
            for (int i = 0; i < this.workersCount; i++) {
                if (this.workers.get(i).getId() == citizen.getId()) {
                    this.workers.remove(i);
                    this.workersCount--;
                    this.citizens.get(i).setWorkplace(null);
                    System.out.println("Worker removed");
                    break;
                }
            }
            throw new BuildingException("Worker not found");
        } else {
            throw new BuildingException("No worker to remove");
        }
    }

    /*
     * Returns the number of citizens living in the building
     * */
    public int getNumberofCitizens()
    {
        return this.citizensCount;
    }

    /*
     * Returns the number of workers working in the building
     * */
    public int getNumberofWorkers()
    {
        return this.workersCount;
    }

    /*
    * Returns true if the building is a home
    * */
    public boolean isAHome()
    {
        return this.citizensCapacity > 0;
    }
}
